# name: CCC
channels:
  - conda-forge
  - anaconda
  - bioconda
  - defaults
dependencies:
- python
- pip
- anndata>=0.7.6
- leidenalg>=0.9.0
- networkx>=2.5.1
- numpy>=1.19.5
- pandas>=1.3.5
- plotly>=5.3.1
- pot>=0.8.0
- pysal>=2.6.0
- python-igraph>=0.9.9
- python-louvain>=0.15
- scanpy>=1.8.2
- scikit-learn>=1.0.2
- importlib-metadata
- ipykernel
- pygraphviz
- pip:
  # - git+https://github.com/benedekrozemberczki/karateclub.git@d750b33
  - karateclub-master.zip